//! Generates reflection tables from the source at compile time so
//! `%builtins` / `%aliases` / `%perl_compats` / `%extensions` never drift.
//!
//! Emits `$OUT_DIR/reflection.rs` with:
//!   - `BUILTIN_ARMS: &[&[&str]]`   — per-arm names from `try_builtin` (used
//!     for the `%aliases` alias → primary map).
//!   - `PERL_COMPATS: &[&str]`      — names recognized by `is_perl_keyword`.
//!   - `PERLRS_EXTENSIONS: &[&str]` — names flagged by `perlrs_extension_name`.
//!
//! `%builtins` itself is built at interpreter init as the union of the two
//! lists above (`perl_compat + extensions`), since that's the true source of
//! "what the language knows about".

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/builtins.rs");
    println!("cargo:rerun-if-changed=src/parser.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let builtins_src = fs::read_to_string("src/builtins.rs").expect("read src/builtins.rs");
    let parser_src = fs::read_to_string("src/parser.rs").expect("read src/parser.rs");

    let arms = extract_try_builtin_arms(&builtins_src);
    let compats = extract_perl_compats(&parser_src);
    let extensions = extract_perlrs_extensions(&parser_src);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = PathBuf::from(out_dir).join("reflection.rs");

    let mut body = String::new();
    body.push_str("// GENERATED by build.rs — do not edit.\n\n");

    body.push_str("pub(crate) const BUILTIN_ARMS: &[&[&str]] = &[\n");
    for arm in &arms {
        body.push_str("    &[");
        for (i, n) in arm.iter().enumerate() {
            if i > 0 {
                body.push_str(", ");
            }
            body.push_str(&format!("{:?}", n));
        }
        body.push_str("],\n");
    }
    body.push_str("];\n\n");

    body.push_str("pub(crate) const PERL_COMPATS: &[&str] = &[\n");
    for n in &compats {
        body.push_str(&format!("    {:?},\n", n));
    }
    body.push_str("];\n\n");

    body.push_str("pub(crate) const PERLRS_EXTENSIONS: &[&str] = &[\n");
    for n in &extensions {
        body.push_str(&format!("    {:?},\n", n));
    }
    body.push_str("];\n");

    fs::write(&dest, body).expect("write reflection.rs");
}

/// Scan `pub(crate) fn try_builtin` for every `"a" | "b" => …` arm and return
/// the names per arm (preserving source order).
fn extract_try_builtin_arms(src: &str) -> Vec<Vec<String>> {
    let fn_pos = src
        .find("pub(crate) fn try_builtin")
        .expect("try_builtin not found");
    let after = &src[fn_pos..];
    let match_rel = after
        .find("match name {")
        .expect("`match name {` not found inside try_builtin");
    let body_start = fn_pos + match_rel + "match name {".len();

    let bytes = src.as_bytes();
    let body_end = find_matching_rbrace(bytes, body_start);
    let body = &src[body_start..body_end];

    let mut arms: Vec<Vec<String>> = Vec::new();
    let bb = body.as_bytes();
    let mut inner = 0i32;
    let mut arm_start = 0usize;
    let mut i = 0usize;
    while i < body.len() {
        let c = bb[i];
        if c == b'"' {
            i = skip_string(bb, i);
            continue;
        }
        if c == b'/' && bb.get(i + 1) == Some(&b'/') {
            while i < body.len() && bb[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        match c {
            b'{' => inner += 1,
            b'}' => inner -= 1,
            b',' if inner == 0 => arm_start = i + 1,
            b'=' if inner == 0 && bb.get(i + 1) == Some(&b'>') => {
                let mut names = Vec::new();
                extract_quoted(&body[arm_start..i], &mut names);
                if !names.is_empty() {
                    arms.push(names);
                }
                i += 2;
                continue;
            }
            _ => {}
        }
        i += 1;
    }
    arms
}

/// Scan `fn perlrs_extension_name` for the quoted names in its `match name { … }`.
fn extract_perlrs_extensions(src: &str) -> Vec<String> {
    let fn_pos = src
        .find("fn perlrs_extension_name")
        .expect("perlrs_extension_name not found");
    let after = &src[fn_pos..];
    let match_rel = after
        .find("match name {")
        .expect("`match name {` not found inside perlrs_extension_name");
    let body_start = fn_pos + match_rel + "match name {".len();

    let bytes = src.as_bytes();
    let body_end = find_matching_rbrace(bytes, body_start);
    let slice = &src[body_start..body_end];

    let mut names = Vec::new();
    extract_quoted(slice, &mut names);
    names.sort();
    names.dedup();
    names
}

/// Scan `fn is_perl5_core` for the `matches!(name, "a" | "b" | …)` list.
/// This is the Perl 5 core-only set — extensions live in
/// `perlrs_extension_name` and are scanned separately.
fn extract_perl_compats(src: &str) -> Vec<String> {
    let fn_pos = src
        .find("fn is_perl5_core")
        .expect("is_perl5_core not found");
    let after = &src[fn_pos..];
    let matches_rel = after
        .find("matches!(")
        .expect("`matches!(` not found inside is_perl_keyword");
    let call_start = fn_pos + matches_rel + "matches!(".len();

    // Walk until the matching `)` at depth 0 relative to the `matches!` call.
    let bytes = src.as_bytes();
    let mut depth = 1i32;
    let mut i = call_start;
    let call_end = loop {
        if i >= src.len() {
            panic!("unterminated matches!(...) in is_perl_keyword");
        }
        let c = bytes[i];
        if c == b'"' {
            i = skip_string(bytes, i);
            continue;
        }
        match c {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    break i;
                }
            }
            _ => {}
        }
        i += 1;
    };

    let slice = &src[call_start..call_end];
    let mut names = Vec::new();
    extract_quoted(slice, &mut names);
    names.sort();
    names.dedup();
    names
}

fn find_matching_rbrace(bytes: &[u8], start: usize) -> usize {
    let mut depth = 1i32;
    let mut i = start;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'"' {
            i = skip_string(bytes, i);
            continue;
        }
        if c == b'/' && bytes.get(i + 1) == Some(&b'/') {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        match c {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return i;
                }
            }
            _ => {}
        }
        i += 1;
    }
    panic!("unterminated brace block starting at {}", start);
}

fn skip_string(bytes: &[u8], mut i: usize) -> usize {
    i += 1;
    while i < bytes.len() {
        if bytes[i] == b'\\' {
            i = (i + 2).min(bytes.len());
            continue;
        }
        if bytes[i] == b'"' {
            return i + 1;
        }
        i += 1;
    }
    i
}

fn extract_quoted(slice: &str, out: &mut Vec<String>) {
    let bytes = slice.as_bytes();
    let mut i = 0usize;
    while i < slice.len() {
        if bytes[i] == b'"' {
            let start = i + 1;
            let mut j = start;
            while j < slice.len() && bytes[j] != b'"' {
                if bytes[j] == b'\\' {
                    j = (j + 2).min(slice.len());
                    continue;
                }
                j += 1;
            }
            if j > start {
                out.push(slice[start..j].to_string());
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
}
