//! Auto-generated by `s_web build`. This binary embeds every .stk file
//! from the user's app directory plus the framework runtime, so it
//! ships as a single self-contained executable with no runtime deps
//! beyond libc + libssl.
//!
//! Architecture:
//!   1. The `EMBEDDED` map below holds every app file as a `&'static str`.
//!   2. `boot()` writes those files into a temp dir at startup so
//!      stryke's `require` / `glob` resolves them off disk like normal.
//!   3. We then drive the framework directly: open SQLite, load all
//!      models/controllers/migrations, run pending migrations, register
//!      routes, and call `web_boot_application` on the configured port.

use std::env;
use std::fs;
use std::path::PathBuf;
use stryke::interpreter::Interpreter;

/// (path-from-app-root, content) pairs. Generated by the s_web build
/// step and inserted between the BEGIN/END markers below.
static EMBEDDED: &[(&str, &str)] = &[
    // BEGIN_EMBEDDED_FILES
{{embedded_entries}}
    // END_EMBEDDED_FILES
];

fn write_app_to(dest: &PathBuf) -> std::io::Result<()> {
    for (rel, body) in EMBEDDED {
        let target = dest.join(rel);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(target, body)?;
    }
    Ok(())
}

fn main() {
    let app_dir = env::var("STRYKE_APP_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let tmp = env::temp_dir().join(format!("stryke_app_{}", std::process::id()));
            tmp
        });
    if !app_dir.exists() || env::var("STRYKE_REINSTALL").is_ok() {
        if let Err(e) = write_app_to(&app_dir) {
            eprintln!("stryke_web: failed to materialize app at {:?}: {}", app_dir, e);
            std::process::exit(1);
        }
    }
    if let Err(e) = env::set_current_dir(&app_dir) {
        eprintln!("stryke_web: cd {:?}: {}", app_dir, e);
        std::process::exit(1);
    }

    let env_name = env::var("STRYKE_ENV").unwrap_or_else(|_| "production".to_string());
    let port: i64 = env::var("PORT")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(3000);

    let mut interp = Interpreter::new();
    let bootstrap = format!(
        r#"
require "./config/application.stk";
my $db_path = "db/{env}.sqlite3";
web_db_connect("sqlite://$db_path");
require "app/models/application_record.stk";
for my $f (glob "app/models/**/*.stk") {{
    next if $f =~ /application_record\.stk$/;
    require $f;
}}
for my $f (glob "app/controllers/**/*.stk") {{ require $f }}
for my $f (glob "app/jobs/**/*.stk")        {{ require $f }}
for my $f (glob "app/mailers/**/*.stk")     {{ require $f }}
for my $f (glob "app/channels/**/*.stk")    {{ require $f }}
for my $f (glob "db/migrate/**/*.stk")      {{ require $f }}
web_migrate();
require "./config/routes.stk";
web_boot_application({port});
"#,
        env = env_name,
        port = port,
    );
    if let Err(e) = stryke::parse_and_run_string(&bootstrap, &mut interp) {
        eprintln!("stryke_web: boot failed: {}", e);
        std::process::exit(1);
    }
}
